### ISSUE TITLE
IOS 12 stopDownload causes downloadFile promise to never resolve

### ISSUE THREAD

**Issue by MarkEAllan** [itinance/react-native-fs#568]
I have noticed that on IOS 12 if a download started by a call to RNFS.downloadFile is cancelled by calling the RNFS.stopDownload, then the promise returned by RNFS.downloadFile is never resolved. This causes our app to never remove a modal progress screen from display.

This only happens on IOS 12. It is fine on IOS 11.4 (and lower) and Android.

I am happy to share the code if required.

**Comment by XiaoMengDuan** [comment]
Any solution? I am facing same isssue.

**Comment by manjariParthiban** [comment]
@XiaoMengDuan I am not sure if this is the right solution, but the following worked for me.

In the Downloader.m file,
Replace 'stopDownload' with the following,

- (void)stopDownload
{
  if (_task.state == NSURLSessionTaskStateRunning) {
    [_task cancel];
    // [_task cancelByProducingResumeData:^(NSData * _Nullable resumeData) {
    //     if (resumeData != nil) {
    //         self.resumeData = resumeData;
    //         _params.resumableCallback();
    //     } else {
            NSError *error = [NSError errorWithDomain:@"RNFS"
                                                 code:@"Aborted"
                                             userInfo:@{
                                                        NSLocalizedDescriptionKey: @"Download has been aborted"
                                                        }];
            
           return _params.errorCallback(error);
        // }
    // }];

  }
}

**Comment by XiaoMengDuan** [comment]
@manjariParthiban Thanks for your solution.
It seems resumableCallback do not cause the rejection of downloadFile promise.
I do not need resume download, so [_task cancel] is fine.
Thanks again.

**Comment by skantus** [comment]
Did you try passing the `jobId` as parameter?

`RNFS. stopDownload(jobId)`

https://github.com/itinance/react-native-fs#stopdownloadjobid-number-void

**Comment by XiaoMengDuan** [comment]
I am using newest version 2.16.1 and It is working as expected on IOS 13
But I do not have any device on IOS 12 to test if this already fixed in newest version.

**Comment by newfylox** [comment]
Guys, having this issue with whatever version of this library using IOS 13.3. Any help? Is this repo still active?

**Comment by humble-programmer** [comment]
Any updates on this? This issue still very much exists. Makes the stopDownload function practically unusable on iOS.
