### ISSUE TITLE
Failed to build with RN 0.61 React/RCTImageLoader.h file not found

### ISSUE THREAD

**Issue by buraky84** [itinance/react-native-fs#768]
RNFSManager.m fatal error: React/RCTImageLoader.h file not found during IOS build

Looks like RCTImageLoader is removed from React Native Libraries. Anyone can suggest a permanent / temporary fix?

Same issue is observed for other libraries too.
https://github.com/ivpusic/react-native-image-crop-picker/issues/692#issuecomment-529017012

I have tried adding `RCTImage` to RNFS.podspec file manually but i could not succeed to prevent failure.

**Comment by richardfelkl** [comment]
Same issue here.

**Comment by fenderface66** [comment]
I am using `^2.14.1` and am still getting this issue. Here is my PodFile:

```
platform :ios, '9.0'
target 'familyApp' do

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'Analytics'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/DynamicLinks', '~> 6.2.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Intercom'

  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store/ios'


  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

**Comment by chase-patterson** [comment]
I have the opposite problem: I'm on React Native 0.60.5 and versions newer than 2.14.1 break my iOS build with `React/RCTImageLoaderProtocol.h` not found. Not sure if you're worried about backwards compatibility, but I can put in a PR on the Readme at least.

**Comment by MagicWangEr** [comment]
#import <React/RCTImageLoaderProtocol.h> 
=>
#import <React/RCTImageLoader.h>

**Comment by roots-ai** [comment]
> RNFSManager.m fatal error: React/RCTImageLoader.h file not found during IOS build
> 
> Looks like RCTImageLoader is removed from React Native Libraries. Anyone can suggest a permanent / temporary fix?
> 
> Same issue is observed for other libraries too.
> [ivpusic/react-native-image-crop-picker#692 (comment)](https://github.com/ivpusic/react-native-image-crop-picker/issues/692#issuecomment-529017012)
> 
> I have tried adding `RCTImage` to RNFS.podspec file manually but i could not succeed to prevent failure.

Any updates here?

**Comment by ackratos** [comment]
Same issue here.



> #import <React/RCTImageLoaderProtocol.h>
> =>
> #import <React/RCTImageLoader.h>

Same issue here. But this works for me locally

**Comment by roots-ai** [comment]
[Resolved] 
1. Clean the derived data folder. 
2. Make sure the dependencies are matching with the installed version of RN.
3. Clean and build it works.

**Comment by MorgadoKnivet** [comment]
+1

**Comment by alfonsodev** [comment]
fresh project  created with 
```
npx react-native init avid --template react-native-template-typescript@6.2.0
```
it uses  `react-native 0.61.2 `

Still fails to build  
```
myProject/node_modules/react-native-fs/RNFSManager.m:17:9: 'React/RCTImageLoaderProtocol.h' file not found
```

**Comment by feedcast-me** [comment]
Any solutions for this?

**Comment by chgsilva** [comment]
+1

**Comment by kylanhurt** [comment]
This issue has been driving me nuts for weeks!

**Comment by darsodango** [comment]
any solution for this? it would be a great help if this will be fixed sooner.

**Comment by davidten** [comment]
```
#if __has_include(<React/RCTImageLoader.h>)
#import <React/RCTImageLoader.h>
#else
#import <React/RCTImageLoaderProtocol.h>
#endif
```

This worked for me

**Comment by itinance** [comment]
Thanx for this, @davidten ! Just published 2.16.3 with this include-bridge.
